# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoginWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(300, 400)
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        LoginWindow.setFont(font)
        self.label = QtWidgets.QLabel(LoginWindow)
        self.label.setGeometry(QtCore.QRect(0, 0, 300, 400))
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setObjectName("label")
        self.username_input = QtWidgets.QLineEdit(LoginWindow)
        self.username_input.setGeometry(QtCore.QRect(100, 100, 150, 20))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.username_input.setFont(font)
        self.username_input.setStyleSheet("")
        self.username_input.setObjectName("username_input")
        self.password_input = QtWidgets.QLineEdit(LoginWindow)
        self.password_input.setGeometry(QtCore.QRect(100, 150, 150, 20))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.password_input.setFont(font)
        self.password_input.setStyleSheet("")
        self.password_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_input.setObjectName("password_input")
        self.login_button = QtWidgets.QPushButton(LoginWindow)
        self.login_button.setGeometry(QtCore.QRect(50, 300, 200, 50))
        self.login_button.setObjectName("login_button")
        self.label_2 = QtWidgets.QLabel(LoginWindow)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 80, 31))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(LoginWindow)
        self.label_3.setGeometry(QtCore.QRect(20, 150, 71, 31))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.remember_checkbox = QtWidgets.QCheckBox(LoginWindow)
        self.remember_checkbox.setGeometry(QtCore.QRect(80, 210, 161, 41))
        self.remember_checkbox.setChecked(True)
        self.remember_checkbox.setObjectName("remember_checkbox")

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "登陆"))
        self.username_input.setPlaceholderText(_translate("LoginWindow", "抗网登陆账号"))
        self.password_input.setPlaceholderText(_translate("LoginWindow", "密码"))
        self.login_button.setText(_translate("LoginWindow", "登陆"))
        self.label_2.setText(_translate("LoginWindow", "用户名："))
        self.label_3.setText(_translate("LoginWindow", "密    码："))
        self.remember_checkbox.setText(_translate("LoginWindow", "记住密码"))
