# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoginWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(300, 400)
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        LoginWindow.setFont(font)
        self.label = QtWidgets.QLabel(LoginWindow)
        self.label.setGeometry(QtCore.QRect(0, 0, 300, 400))
        self.label.setStyleSheet("background-color: rgb(89, 175, 232);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.username = QtWidgets.QLineEdit(LoginWindow)
        self.username.setGeometry(QtCore.QRect(100, 100, 150, 20))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.username.setFont(font)
        self.username.setStyleSheet("background-color: rgb(56, 255, 172);\n"
"color: rgb(0, 85, 0);")
        self.username.setObjectName("username")
        self.password = QtWidgets.QLineEdit(LoginWindow)
        self.password.setGeometry(QtCore.QRect(100, 150, 150, 20))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.password.setFont(font)
        self.password.setStyleSheet("background-color: rgb(56, 255, 172);\n"
"color: rgb(0, 85, 0);")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.btn_login = QtWidgets.QPushButton(LoginWindow)
        self.btn_login.setGeometry(QtCore.QRect(50, 300, 200, 50))
        self.btn_login.setObjectName("btn_login")
        self.label_2 = QtWidgets.QLabel(LoginWindow)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 80, 31))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(LoginWindow)
        self.label_3.setGeometry(QtCore.QRect(20, 150, 71, 31))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.remember = QtWidgets.QCheckBox(LoginWindow)
        self.remember.setGeometry(QtCore.QRect(80, 210, 161, 41))
        self.remember.setObjectName("remember")

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "Form"))
        self.username.setPlaceholderText(_translate("LoginWindow", "抗网登陆账号"))
        self.password.setPlaceholderText(_translate("LoginWindow", "密码"))
        self.btn_login.setText(_translate("LoginWindow", "登陆"))
        self.label_2.setText(_translate("LoginWindow", "用户名："))
        self.label_3.setText(_translate("LoginWindow", "密    码："))
        self.remember.setText(_translate("LoginWindow", "记住密码"))
